services:
  todo-frontend:
    image: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/
    container_name: todo-frontend
  debug-helper:
    image: busybox
  todo-backend:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - redis
      - mongo
    container_name: todo-backend
  mongo:
    image: mongo
    restart: always
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo
  redis:
    image: redis
    ports:
      - 6378:6379
    command: [ 'redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis
  nginx:
    image: nginx:1.20.1
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    depends_on:
      - todo-frontend
      - todo-backend
volumes:
  mongo_data:
  redis_data: